### ISSUE TITLE
yardoc broken in Ruby 2.2

### ISSUE THREAD

**Issue by uberllama** [lsegal/yard#825]
I have a Rails 4.2 project and after updating from Ruby 2.1.4 to 2.2.0, yardoc no longer runs. I tried switching my project back to 2.1.4 and it ran with no issues, so I know its not a syntax issue or other bug I've introduced along with the update.

Here's the stack trace:

```
littleblimp:foo yuval$ yardoc
/Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:460:in `block (2 levels) in on_params': undefined method `type' for 6504:Fixnum (NoMethodError)
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `map!'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `block in on_params'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `map!'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `on_params'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/gems/yard-0.8.7.6/bin/yardoc:12:in `<top (required)>'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/bin/yardoc:23:in `load'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/bin/yardoc:23:in `<main>'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/bin/ruby_executable_hooks:15:in `eval'
	from /Users/yuval/.rvm/gems/ruby-2.2.0@foo/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lsegal** [comment]
Yup, it's a regression in Ruby-- I *just* reported it a few hours ago: https://bugs.ruby-lang.org/issues/10693

**Comment by lsegal** [comment]
FWIW a workaround would be to use `--legacy` in 2.2, though you might want to just stick to 2.1.x for now.

**Comment by uberllama** [comment]
That has to be the fastest issue response of all time. :) So the issue is with my keyword args then. Very sad.

**Comment by dogweather** [comment]
Does anyone know how to view the actual revision itself from  https://bugs.ruby-lang.org/issues/10693 ? I can't find a link to the actual code changes.

**Comment by lsegal** [comment]
@dogweather https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/49140/diff/

**Comment by dmolesUC3** [comment]
The underlying Ruby bug is fixed in 2.2.1, which was [released on March 3](https://www.ruby-lang.org/en/news/2015/03/03/ruby-2-2-1-released/).

**Comment by lsegal** [comment]
Sweet thanks for letting us know @dmolesUC3! We can close this now.

**Comment by dmolesUC3** [comment]
No problem!

**Comment by bilus** [comment]
I still see it with 2.2.3p173 and yard 0.8.7.6

**Comment by brasten** [comment]
Yeah, ruby 2.2.2p95 & yard 0.8.7.6. Seeing it here.

**Comment by lsegal** [comment]
If you are still experiencing this please provide an updated backtrace that shows the issue just to be sure that it is the same issue. Thanks!

**Comment by heero-yuy** [comment]
Still getting this with Ruby 2.2.0 and version 0.8.7.6, removing the keyword arguments fixed it. Here's the backtrace:

    /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:460:in `block (2 levels) in on_params': undefined method `type' for    20840:Fixnum (NoMethodError)
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `map!'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:458:in `block in on_params'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `map!'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:454:in `on_params'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:50:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/ruby/ruby_parser.rb:15:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:439:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:44:in `block in parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:70:in `capture'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:43:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:368:in `parse_in_order'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:107:in `block in parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/logging.rb:166:in `enter_level'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/parser/source_parser.rb:106:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard.rb:18:in `parse'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/yardoc.rb:249:in `run'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/lib/yard/cli/command.rb:13:in `run'
    	from /Users/test/.rvm/gems/ruby-2.2.0/gems/yard-0.8.7.6/bin/yardoc:12:in `<top (required)>'
    	from /Users/test/.rvm/gems/ruby-2.2.0/bin/yardoc:23:in `load'
    	from /Users/test/.rvm/gems/ruby-2.2.0/bin/yardoc:23:in `<main>'
    	from /Users/test/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
    	from /Users/test/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by lsegal** [comment]
@heero-yuy the bug was fixed in Ruby 2.2.1. If you need to use 2.2.0, you should open a report with Ruby to ask for the patch to be backported. This is still a third-party regression in Ripper that cannot be resolved in YARD.

**Comment by heero-yuy** [comment]
@lsegal My apologizes! Just looked at the other duplicates and saw it doesn't persist >=2.2.1. Thank you!
