### ISSUE TITLE
YARD::DocstringParser's after_parse can't handle Symbol parameters

### ISSUE THREAD

**Issue by KronicDeth** [lsegal/yard#530]
[error]: Unhandled exception in WebFeedParser::CacheDimensionHandler:
[error]:   in `lib/*/*/transformation.rb`:8:

```
8: cache_dimension :source,
```

[error]: NoMethodError: undefined method `gsub' for :source:Symbol
[error]: Stack trace:
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:250:in`block (2 levels) in class:DocstringParser'
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:250:in `map'
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:250:in`block in class:DocstringParser'
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:239:in `call'
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:239:in`block in call_after_parse_callbacks'
    /Users/lukeimhoff/.rvm/gems/ruby-1.9.2-p290@web_feed_parser/gems/yard-0.8.0/lib/yard/docstring_parser.rb:238:in `each'

This worked in 0.7.5.  I may be just declaring my custom handler incorrectly.  Here's the head of the handler:

``` ruby
class WebFeedParser::CacheDimensionHandler < YARD::Handlers::Ruby::Base
  handles method_call(:cache_dimension)
  namespace_only

  # Uses parameters to cache_dimension to construct signature and docstring for method defined by cache_dimension.
  # All documentation is grouped under Dimension Caches.
  def process
```
